name: CI/CD for Training Service

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: training-service
  K8S_CRONJOB_NAME: self-healing-cronjob

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
      
      - name: Update deployment manifest
        # ADDED: This step updates the image tag in your deployment file.
        # Assumes your file is located at 'kubernetes/deployment.yaml'.
        run: |
          sed -i "s|image: .*|image: yashwanthydg/training-service:${{ github.sha }}|g" kubernetes/cronjob.yaml
  
      - name: Commit and push manifest changes
        # ADDED: This step commits the updated manifest file back to your main branch.
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add kubernetes/manifest.yaml
          git diff --staged --quiet || git commit -m "CI: Update image tag to ${{ github.sha }}"
          git push


  deploy:
    name: Deploy to Kubernetes
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Deploy CronJob Update
        run: |
          kubectl set image cronjob/${{ env.K8S_CRONJOB_NAME }} ${{ env.DOCKER_IMAGE_NAME }}=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          echo "CronJob image updated successfully!"
